### ISSUE TITLE
pid算法输出问题

### ISSUE THREAD

**Issue by adeansHFUT** [RT-Thread-packages/rt-robot#20]
` pid->p_error = pid->kp * pid->error;
  pid->i_error = pid->ki * pid->integral;
  pid->d_error = pid->kd * (pid->error - 2 * pid->error_l + pid->error_ll);

  pid->out = pid->p_error + pid->i_error + pid->d_error; `
这段代码是增量式pid还是位置式pid，p_error 和i_error是位置式的表示，d_error又是增量式的表示了

**Comment by sogwms** [comment]
控制算法正在更新中
