### ISSUE TITLE
ab_phase_encoder现在可以用了吗

### ISSUE THREAD

**Issue by gobelieve2** [RT-Thread-packages/rt-robot#25]
ab_phase_encoder_t ab_phase_encoder_create(rt_base_t pin_a, rt_base_t pin_b, rt_uint16_t pulse_revol)
参数pulse_revol是指中断频率？
能多提供一点使用说明吗

**Comment by yqiu2018** [comment]
@sogwms

**Comment by sogwms** [comment]
@gobelieve2 可以用， pulse_revol 是车轮转一圈输出的脉冲数
