### ISSUE TITLE
亲爱的作者，我还想了解轮子半径，横向和纵向轴距，减速比，编码器每圈的转速等各种参数之间的关系以及最后和控制部分的联系，请问还有这方面的说明讲解吗，非常感谢。

### ISSUE THREAD

**Issue by cbwznb** [RT-Thread-packages/rt-robot#45]

**Comment by wuhanstudio** [comment]
- 轮子半径，横向和纵向轴距 (eq. 14, eq.15 & eq. 20, eq.21)

https://research.ijcaonline.org/volume113/number3/pxc3901586.pdf

- 减速比 (GEAR_RATIO)

- 编码器 （https://www.chiefdelphi.com/t/encoders-velocity-to-m-s/390332）
